# Generated by Django 5.0.2 on 2024-02-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_messages_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_to',
            field=models.CharField(default='emerie', max_length=100),
        ),
    ]
